### ISSUE TITLE
Test CI with master, 1, and LTS

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/SparseArrays.jl#8]
We are currently testing only master, but presumably we should test both the latest stable release as well as LTS. In SuiteSparse, we enabled latest stable testing.

@DilumAluthge Are there any best practices here?

**Comment by KristofferC** [comment]
In Pkg, we test master Pkg only on master. And then we have `release-1.6`, `release-1.7` branches that we backport to that run tests on the respective Julia version.

**Comment by DilumAluthge** [comment]
On the subject of backporting, would it be useful for us to install a backport GitHub Action on this repository?

For JuliaLang/julia, I think the current system (where Kristoffer manually runs the https://github.com/KristofferC/Backporter script on his local machine) works very well. However, for stdlibs that live in external repos, I don't know if this is scalable, since now Kristoffer will have to run the script `N + 1` times (if there are `N` stdlibs that live in external repos).

So, for some of these external stdlibs, perhaps we could install a backport GitHub Action, and use that instead? For example: https://github.com/tibdex/backport

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/SparseArrays.jl/pull/62

**Comment by ViralBShah** [comment]
Will these backports go to julialang/Julia?

**Comment by KristofferC** [comment]
No, they would go to a `release-1.6`, `release-1.7` branch on this repo. But to create them we would need to do the same thing as we did for the master branch here (extract all commits that affected SparseArrays) but do it for the  Julia`release-1.6`, `release-1.7` branches. I don't think that should be too difficult.
